"use server";

import fs from "fs";
import path from "path";
import { revalidatePath } from "next/cache";

export async function updateProduct(productData: any) {
  try {
    const filePath = path.join(process.cwd(), "src/data/products.ts");
    
    // Import current data directly
    const { PHILIPS_PRODUCTS } = await import("@/data/products");
    
    // Update the specific product
    const updatedProducts = PHILIPS_PRODUCTS.map((p: any) => 
      p.id === productData.id ? { ...p, ...productData } : p
    );

    // Completely replace the file
    const fileContent = `/* ============================================================
   HAMEDCO — Philips Ultrasound Product Catalog
   Generated by HAMEDCO CMS
   ============================================================ */

export const PHILIPS_PRODUCTS = ${JSON.stringify(updatedProducts, null, 2)};
`;

    fs.writeFileSync(filePath, fileContent, "utf-8");
    
    // Revalidate paths for Next.js to clear cache
    revalidatePath("/admin/san-pham");
    revalidatePath("/san-pham");
    revalidatePath(`/san-pham/${productData.slug}`);
    
    return { success: true };
  } catch (err: any) {
    console.error("Failed to save product:", err);
    return { success: false, error: err.message };
  }
}
